-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 07:41:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema humhub_prod_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema humhub_prod_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `humhub_prod_db` DEFAULT CHARACTER SET utf8 ;
USE `humhub_prod_db` ;

-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_communes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_communes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(256) NULL DEFAULT NULL,
  `Latitude` VARCHAR(64) NULL DEFAULT NULL,
  `Longitude` VARCHAR(64) NULL DEFAULT NULL,
  `commune` VARCHAR(256) NULL DEFAULT NULL,
  `code_postal` VARCHAR(16) NULL DEFAULT NULL,
  `code_departement` VARCHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_infos_producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_infos_producteur` (
  `prod_inscrit` VARCHAR(8) NULL DEFAULT NULL,
  `fournisseur_cet` VARCHAR(8) NULL DEFAULT NULL,
  `niv_certif_ab` INT(11) NULL DEFAULT NULL,
  `orgcertifbio` VARCHAR(128) NULL DEFAULT NULL,
  `urlcertifab` VARCHAR(256) NULL DEFAULT NULL,
  `surfacehectterres` VARCHAR(32) NULL DEFAULT NULL,
  `surfacesousserre` VARCHAR(32) NULL DEFAULT NULL,
  `tetes_betail` VARCHAR(32) NULL DEFAULT NULL,
  `hl_par_an` VARCHAR(32) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_entite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_entite` (
  `name` VARCHAR(256) NULL DEFAULT NULL,
  `type` VARCHAR(16) NULL DEFAULT NULL,
  `street` VARCHAR(256) NULL DEFAULT NULL,
  `zip` VARCHAR(16) NULL DEFAULT NULL,
  `city` VARCHAR(256) NULL DEFAULT NULL,
  `country` VARCHAR(256) NULL DEFAULT NULL,
  `state` VARCHAR(256) NULL DEFAULT NULL,
  `latitude` VARCHAR(64) NULL DEFAULT NULL,
  `longitude` VARCHAR(64) NULL DEFAULT NULL,
  `pk` INT NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `isActive` BIT(1) NULL DEFAULT b'1',
  `telFixe` VARCHAR(32) NULL DEFAULT NULL,
  `telMobile` VARCHAR(32) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `contactPrenom` VARCHAR(64) NULL DEFAULT NULL,
  `contactNom` VARCHAR(64) NULL DEFAULT NULL,
  `siret` VARCHAR(16) NULL DEFAULT NULL,
  `urlWeb` VARCHAR(256) NULL DEFAULT NULL,
  `urlFb` VARCHAR(256) NULL DEFAULT NULL,
  `urlIg` VARCHAR(256) NULL DEFAULT NULL,
  `urlTwitter` VARCHAR(256) NULL DEFAULT NULL,
  `urlBoutique` VARCHAR(256) NULL DEFAULT NULL,
  `commentaire` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cet_entite_cet_infos_producteur1_idx` (`pk` ASC),
  CONSTRAINT `fk_cet_entite_cet_infos_producteur1`
    FOREIGN KEY (`pk`)
    REFERENCES `humhub_prod_db`.`cet_infos_producteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(128) NULL DEFAULT NULL,
  `sous_type` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_producteur_lieu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_producteur_lieu` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Fk_producteur` INT(11) NOT NULL,
  `Fk_lieu` INT(11) NOT NULL,
  `Fk_type` INT(11) NOT NULL,
  `nom` VARCHAR(256) NULL DEFAULT NULL,
  `precisions` VARCHAR(1024) NULL DEFAULT NULL,
  `date` VARCHAR(32) NULL DEFAULT NULL,
  `Heure_deb` VARCHAR(32) NULL DEFAULT NULL,
  `Heure_fin` VARCHAR(32) NULL DEFAULT NULL,
  `jour` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `Fk_lieu` (`Fk_lieu` ASC),
  INDEX `fk_type_producteur_lieu` (`Fk_type` ASC),
  INDEX `fk_cet_producteur_lieu_cet_infos_producteur1_idx` (`Fk_producteur` ASC),
  CONSTRAINT `Fk_lieu`
    FOREIGN KEY (`Fk_lieu`)
    REFERENCES `humhub_prod_db`.`cet_entite` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_type_producteur_lieu`
    FOREIGN KEY (`Fk_type`)
    REFERENCES `humhub_prod_db`.`cet_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cet_producteur_lieu_cet_infos_producteur1`
    FOREIGN KEY (`Fk_producteur`)
    REFERENCES `humhub_prod_db`.`cet_infos_producteur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_produit` (
  `id` INT(11) NOT NULL,
  `categorie` VARCHAR(128) NULL DEFAULT NULL,
  `nom` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_join_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_join_produit` (
  `Fk_adresse_cet` INT(11) NOT NULL,
  `Fk_produit` INT(11) NOT NULL,
  PRIMARY KEY (`Fk_adresse_cet`, `Fk_produit`),
  INDEX `fk_cet_entite_has_cet_produit_cet_produit1_idx` (`Fk_produit` ASC),
  INDEX `fk_cet_entite_has_cet_produit_cet_entite1_idx` (`Fk_adresse_cet` ASC),
  CONSTRAINT `fk_cet_entite_has_cet_produit_cet_entite1`
    FOREIGN KEY (`Fk_adresse_cet`)
    REFERENCES `humhub_prod_db`.`cet_entite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cet_entite_has_cet_produit_cet_produit1`
    FOREIGN KEY (`Fk_produit`)
    REFERENCES `humhub_prod_db`.`cet_produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `humhub_prod_db`.`cet_join_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `humhub_prod_db`.`cet_join_type` (
  `Fk_adresse_cet` INT(11) NOT NULL,
  `Fk_type` INT(11) NOT NULL,
  PRIMARY KEY (`Fk_adresse_cet`, `Fk_type`),
  INDEX `fk_cet_entite_has_cet_type_cet_type1_idx` (`Fk_type` ASC),
  INDEX `fk_cet_entite_has_cet_type_cet_entite1_idx` (`Fk_adresse_cet` ASC),
  CONSTRAINT `fk_cet_entite_has_cet_type_cet_entite1`
    FOREIGN KEY (`Fk_adresse_cet`)
    REFERENCES `humhub_prod_db`.`cet_entite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cet_entite_has_cet_type_cet_type1`
    FOREIGN KEY (`Fk_type`)
    REFERENCES `humhub_prod_db`.`cet_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
